name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18.2.0" # Or your project's Node.js version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Ensure your build script moves index.html to the root of the `build` directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Change to your build output directory
